# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/msm8976-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gts210velte gts210vewifi gts28velte gts28vewifi,$(TARGET_DEVICE)),)

endif
